# Default values for logstream-workergroup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

rbac:
  create: true
  apiGroups: 
  - core
  resources:
  - pods
  verbs:
  - get
  - list
  annotations: {}

criblImage:
  repository: cribl/cribl
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "3.3.0"

imagePullSecrets: []
nameOverride: "edge-wg"

config: 
  host: logstream.elated-blackburn-a7umuij.cribl.cloud
  group: kubernetes
  token: gYNDCi4w3WC2zpvTMIT9aDSSr6Ne7gkY
  rejectSelfSignedCerts: 0
  healthPort: 9000
  tlsLeader:
    enable: true
  probes: false


deployment: daemonset
nodeSelector: 
  alpha.eksctl.io/nodegroup-name: demo-instrumented
# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: alpha.eksctl.io/nodegroup-name
#           operator: In
#           values:
#           - demo-instrumented
hostNetwork: true
extraVolumeMounts:
  - name: hostroot
    mountPath: /hostfs
    hostPath: /
env:
  CRIBL_DIST_MODE: managed-edge

podAnnotations: {}


# service:
#   type: LoadBalancer
#   annotations: {}

#   ports:
#   - name: tcpjson
#     port: 10001
#     protocol: TCP
#   - name: s2s
#     port: 9997
#     protocol: TCP
#   - name: http
#     port: 10080
#     protocol: TCP
#   - name: https
#     port: 10081
#     protocol: TCP    
#   - name: syslog
#     port: 5140
#     protocol: TCP
#   - name: metrics
#     port: 8125
#     protocol: TCP
#   - name: elastic
#     port: 9200
#     protocol: TCP

resources: 
  limits:
    cpu: 2000m
    memory: 4096Mi
  requests:
    cpu: 1250m
    memory: 256Mi


# autoscaling:
#   enabled: true
#   minReplicas: 2
#   maxReplicas: 10
#   targetCPUUtilizationPercentage: 50