---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: kickoff22demo
  region: us-east-1
nodeGroups:
  - name: demo-instrumented
    minSize: 2
    maxSize: 4
    desiredCapacity: 2
    privateNetworking: true
    volumeSize: 200
    availabilityZones: ["us-east-1a"]

    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
      withAddonPolicies:
        autoScaler: true
        imageBuilder: true
        ebs: true
    labels: {role: worker}
    tags:
      nodegroup-role: worker
    instancesDistribution:
      instanceTypes: 
        - t3a.small
  - name: demo-uninstrumented
    minSize: 2
    maxSize: 4
    desiredCapacity: 2
    privateNetworking: true
    volumeSize: 200
    availabilityZones: ["us-east-1b"]

    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
      withAddonPolicies:
        autoScaler: true
        imageBuilder: true
        ebs: true
    labels: {role: worker}
    tags:
      nodegroup-role: worker
    instancesDistribution:
      instanceTypes: 
        - t3a.small
