---
apiVersion: v1
kind: Service
metadata:
  name: goatchella
  labels:
    app.kubernetes.io/name: goatchella
  annotations:
    {}
spec:
  type: LoadBalancer
  ports: 
      - port: 80
        targetPort: 80
        protocol: TCP
        name: web
  selector:
    app.kubernetes.io/name: goatchella
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goatchella
  labels:
    app.kubernetes.io/name: goatchella
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: goatchella
  template:
    metadata:
      labels:
        app.kubernetes.io/name: goatchella
    spec:
      containers:
        - name: blog
          image: ghcr.io/pdugas/goatchella
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 2000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi